#!/bin/bash
#
# Sets up all the dependencies, etc. so you can build and test.

set -euo pipefail
source "$(dirname "$0")/utilities.bash"

header "Linter"
gometalinter --deadline=1m --vendored-linters --vendor --disable=gotype

header "Flint"
flint --skip-changelog --skip-code-of-conduct

# vim: set ft=sh :
