#!/bin/bash
#
# Runs all tests & lint.

set -euo pipefail
source "$(dirname "$0")/utilities.bash"

header "Tests"
go test $(glide novendor)

header "Linter"
gometalinter --deadline=1m --vendored-linters --vendor --disable=gotype

# vim: set ft=sh :