#!/bin/bash
#
# Runs all tests & lint.

set -euo pipefail
source "$(dirname "$0")/utilities.bash"

header "Tests"
go test ./...

header "Linter"
gometalinter --deadline=2m --vendored-linters --vendor --disable=gotype

# vim: set ft=sh :
