#!/bin/bash
#
# Generates the version.go file with the current tag.

set -euo pipefail
source "$(dirname "$0")/utilities.bash"

version=$(git describe --tags --long)

header "Updating version.go => ${version}"
cat << EOF > version.go
package main

//go:generate bash ./script/version
var version = "${version}"
EOF

# vim: set ft=sh :
